micronaut:
  application:
    name: learn
  server:
    port: 8082
    h2:
      console:
        enabled: true
        path: /h2
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver

netty:
  default:
    allocator:
      max-order: 3

aerospike:
  hostname: 127.0.0.1
  port: 3000
  namespace: test