micronaut:
  application:
    name: learn
    h2:
      console:
        enabled: true
        path: /h2
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver

netty:
  default:
    allocator:
      max-order: 3
